import { z } from "zod";
import type { QuestionDef } from "./types";

// Short constructors keep the bank readable. zod v4 uses `{ error }`.
const req = (min: number, msg: string) => z.string().min(min, { error: msg });
const opt = () => z.string();

const teamMemberSchema = z.object({
  name: z.string().min(1, { error: "Name is required" }),
  role: z.string().min(1, { error: "Role is required" }),
  bio: z.string().min(10, { error: "Bio must be at least 10 characters" }),
});

/**
 * The single source of truth for the intake.
 *
 * Every other representation — the form renderer, the chat interviewer, the
 * zod schemas, and the AI draft prompt — is derived from this array. Adding a
 * question means adding one entry here and nothing else.
 *
 * Universal questions have no `branch`. Industry follow-ups set both `branch`
 * and `parentId`, so a renderer can nest them under the parent they refine.
 */
export const QUESTION_BANK: QuestionDef[] = [
  // ── Gate ────────────────────────────────────────────────────────────────
  {
    id: "business_type",
    section: "gate",
    order: 0,
    label: "Do you sell to other businesses?",
    helper: "v1 supports B2B companies. B2C and consumer retail are coming later.",
    widget: "radioPills",
    options: [
      { value: "b2b", label: "Yes — we sell to businesses (B2B)" },
      { value: "b2c", label: "No — we sell to consumers (B2C)" },
      { value: "other", label: "A mix of both" },
    ],
    required: true,
    validate: z.enum(["b2b", "b2c", "other"], { error: "Please choose one" }),
    aiSpec: "Whether the company sells to businesses (b2b), consumers (b2c), or both.",
    promptLabel: "Business type",
  },

  // ── Company basics (§4.0) ───────────────────────────────────────────────
  {
    id: "client_name",
    section: "basics",
    order: -2,
    label: "Your name",
    placeholder: "Jane Smith",
    widget: "text",
    required: true,
    validate: req(1, "Your name is required"),
    aiSpec: "The name of the person being interviewed.",
    promptLabel: "Contact name",
  },
  {
    id: "client_email",
    section: "basics",
    order: -1,
    label: "Your email",
    helper: "Where we send your deck when it's ready.",
    placeholder: "jane@company.com",
    widget: "text",
    required: true,
    validate: z.email({ error: "Enter a valid email" }),
    aiSpec: "The email address of the person being interviewed.",
    promptLabel: "Contact email",
  },
  {
    id: "company_name",
    section: "basics",
    order: 0,
    label: "Company name",
    placeholder: "Acme Industrial",
    widget: "text",
    required: true,
    validate: req(1, "Company name is required"),
    aiSpec: "The company's legal or trading name.",
    promptLabel: "Company name",
  },
  {
    id: "website",
    section: "basics",
    order: 1,
    label: "Website",
    placeholder: "acme.com",
    widget: "text",
    required: false,
    validate: opt(),
    aiSpec: "Company website, if they have one.",
    promptLabel: "Website",
  },
  {
    id: "hq_location",
    section: "basics",
    order: 2,
    label: "Headquarters location",
    placeholder: "Mobile, Alabama",
    widget: "text",
    required: true,
    validate: req(2, "HQ location is required"),
    aiSpec: "City and state/country of the head office.",
    promptLabel: "HQ location",
  },
  {
    id: "year_founded",
    section: "basics",
    order: 3,
    label: "Year founded",
    placeholder: "2019",
    widget: "text",
    required: true,
    validate: req(4, "Year founded is required"),
    aiSpec: "The year the company was founded.",
    promptLabel: "Year founded",
  },
  {
    id: "legal_entity",
    section: "basics",
    order: 4,
    label: "Legal entity type",
    widget: "select",
    options: [
      { value: "llc", label: "LLC" },
      { value: "c-corp", label: "C-Corp" },
      { value: "s-corp", label: "S-Corp" },
      { value: "partnership", label: "Partnership" },
      { value: "other", label: "Other" },
    ],
    required: false,
    validate: opt(),
    aiSpec: "Legal structure of the business (LLC, C-Corp, etc.).",
    promptLabel: "Legal entity",
  },
  {
    id: "employee_count",
    section: "basics",
    order: 5,
    label: "Number of employees",
    placeholder: "52",
    widget: "text",
    required: true,
    validate: req(1, "Employee count is required"),
    aiSpec: "Current headcount, including contractors if that is how they count.",
    promptLabel: "Employees",
  },
  {
    id: "industry_branch",
    section: "basics",
    order: 6,
    label: "Which best describes your company?",
    helper: "This decides which follow-up questions we ask you.",
    widget: "radioPills",
    options: [
      { value: "industrial", label: "Industrial" },
      { value: "technology", label: "Technology" },
    ],
    required: true,
    validate: z.enum(["industrial", "technology"], { error: "Please choose one" }),
    aiSpec:
      "Whether this is an Industrial or a Technology company. Ask this EARLY — it determines every later follow-up question.",
    promptLabel: "Industry branch",
  },
  {
    id: "sub_industry",
    section: "basics",
    order: 7,
    label: "Sub-industry",
    placeholder: "Valve repair & industrial services",
    widget: "text",
    required: false,
    validate: opt(),
    aiSpec: "More specific industry description in the founder's own words.",
    promptLabel: "Sub-industry",
  },
  {
    id: "one_liner",
    section: "basics",
    order: 8,
    label: "In one sentence, what do you do?",
    placeholder: "We repair and maintain industrial valves for Gulf Coast refineries.",
    widget: "charTextarea",
    required: true,
    validate: req(10, "Please write at least 10 characters"),
    aiSpec: "A single-sentence description of what the company does.",
    promptLabel: "One-line description",
  },

  // ── Investment thesis (§4.1) ────────────────────────────────────────────
  {
    id: "opportunity",
    section: "thesis",
    order: 0,
    label: "What is the opportunity, in one or two sentences?",
    widget: "charTextarea",
    required: true,
    validate: req(20, "Please describe the opportunity (min 20 characters)"),
    aiSpec: "The core investment opportunity stated in one or two sentences.",
    promptLabel: "The opportunity",
  },
  {
    id: "why_now",
    section: "thesis",
    order: 1,
    label: "Why now? What changed in the market that makes this the right time?",
    helper: "Investors want a reason this is urgent today rather than three years ago.",
    widget: "textarea",
    required: true,
    validate: req(20, "Please explain why now (min 20 characters)"),
    aiSpec: "What changed in the market that makes this the right moment.",
    promptLabel: "Why now",
  },
  {
    id: "why_this_company",
    section: "thesis",
    order: 2,
    label: "Why should an investor put money into this company specifically?",
    widget: "textarea",
    required: true,
    validate: req(20, "Please explain why this company (min 20 characters)"),
    aiSpec: "Why this specific company, versus anyone else solving the same problem.",
    promptLabel: "Why this company",
  },

  // ── Problem (§4.2) ──────────────────────────────────────────────────────
  {
    id: "buyer_profile",
    section: "problem",
    order: 0,
    label: "Who buys from you?",
    helper: "Job title, type of company, and company size.",
    placeholder: "Plant maintenance managers at Gulf Coast refineries, 500+ employees.",
    widget: "textarea",
    required: true,
    validate: req(15, "Please describe your buyer (min 15 characters)"),
    aiSpec: "The buyer: job title, company type, and company size.",
    promptLabel: "Who buys",
  },
  {
    id: "customer_problem",
    section: "problem",
    order: 1,
    label: "What problem do they have?",
    widget: "textarea",
    required: true,
    validate: req(20, "Please describe the problem (min 20 characters)"),
    aiSpec: "The problem the buyer has.",
    promptLabel: "Their problem",
  },
  {
    id: "why_alternatives_fell_short",
    section: "problem",
    order: 2,
    label: "Why have existing options fallen short?",
    widget: "textarea",
    required: true,
    validate: req(20, "Please explain why alternatives fall short (min 20 characters)"),
    aiSpec: "Why the options available before this company were inadequate.",
    promptLabel: "Why existing options fall short",
  },

  // ── Solution & value (§4.3) ─────────────────────────────────────────────
  {
    id: "what_you_sell",
    section: "solution",
    order: 0,
    label: "What do you sell today?",
    helper: "What you actually sell now — not what is on the roadmap.",
    widget: "textarea",
    required: true,
    validate: req(20, "Please describe what you sell (min 20 characters)"),
    aiSpec: "What the company sells today, as distinct from planned products.",
    promptLabel: "What we sell",
  },
  {
    id: "customer_value",
    section: "solution",
    order: 1,
    label: "What value does it deliver to the customer?",
    helper: "Time saved, cost reduced, revenue gained — quantify it if you can.",
    widget: "textarea",
    required: true,
    validate: req(20, "Please describe the value delivered (min 20 characters)"),
    aiSpec: "Quantified customer value: time saved, cost reduced, or revenue gained.",
    promptLabel: "Customer value",
  },
  {
    id: "why_better",
    section: "solution",
    order: 2,
    label: "Why is your option better than the alternatives?",
    widget: "textarea",
    required: true,
    validate: req(20, "Please explain why you're better (min 20 characters)"),
    aiSpec: "Why this option beats the alternatives available to the buyer.",
    promptLabel: "Why we're better",
  },
  {
    id: "tech_hard_to_explain",
    section: "solution",
    order: 3,
    branch: "technology",
    parentId: "what_you_sell",
    label: "Is this product hard to explain to a non-technical finance person?",
    helper: "If yes, we weight the appendix more heavily toward technical proof.",
    widget: "yesNo",
    options: [
      { value: "yes", label: "Yes — it needs technical background" },
      { value: "no", label: "No — it's straightforward" },
    ],
    required: false,
    validate: opt(),
    aiSpec:
      "Whether the product is hard to explain to a non-technical finance audience. Drives appendix depth.",
    promptLabel: "Hard to explain to a non-technical audience",
  },

  // ── Evidence of demand (§4.4) ───────────────────────────────────────────
  {
    id: "customer_count",
    section: "demand",
    order: 0,
    label: "Do you have customers? How many?",
    placeholder: "38 active accounts",
    widget: "text",
    required: true,
    validate: req(1, "Customer count is required"),
    aiSpec: "Whether they have customers and how many.",
    promptLabel: "Customers",
  },
  {
    id: "revenue_ltm",
    section: "demand",
    order: 1,
    label: "Revenue — last 12 months",
    widget: "money",
    required: true,
    validate: req(1, "Last 12 months revenue is required"),
    aiSpec: "Revenue over the last twelve months.",
    promptLabel: "Revenue (last 12 months)",
    allowAttachments: true,
  },
  {
    id: "revenue_prior_year",
    section: "demand",
    order: 2,
    label: "Revenue — prior year",
    widget: "money",
    required: false,
    validate: opt(),
    aiSpec: "Revenue in the year before last, for growth comparison.",
    promptLabel: "Revenue (prior year)",
    allowAttachments: true,
  },
  {
    id: "signed_contracts",
    section: "demand",
    order: 3,
    label: "Do you have signed contracts?",
    helper: "Number, total value, or typical length — whatever you have.",
    widget: "textarea",
    required: false,
    validate: opt(),
    aiSpec: "Signed contracts: count, value, or duration.",
    promptLabel: "Signed contracts",
    allowAttachments: true,
  },
  // Industrial follow-ups
  {
    id: "orders_on_hand",
    section: "demand",
    order: 4,
    branch: "industrial",
    parentId: "customer_count",
    label: "Current orders on hand",
    widget: "textarea",
    required: false,
    validate: opt(),
    aiSpec: "Orders currently on the books awaiting fulfilment.",
    promptLabel: "Orders on hand",
  },
  {
    id: "backlog",
    section: "demand",
    order: 5,
    branch: "industrial",
    parentId: "customer_count",
    label: "Backlog",
    helper: "Both the dollar value and how many months of work it represents.",
    placeholder: "$4.2M — about 7 months of work",
    widget: "textarea",
    required: false,
    validate: opt(),
    aiSpec: "Backlog in dollars and in months of work.",
    promptLabel: "Backlog",
  },
  {
    id: "repeat_customers",
    section: "demand",
    order: 6,
    branch: "industrial",
    parentId: "customer_count",
    label: "Repeat customers",
    helper: "As a share of revenue, or just a count.",
    widget: "text",
    required: false,
    validate: opt(),
    aiSpec: "Repeat customers as a percentage of revenue or as a count.",
    promptLabel: "Repeat customers",
  },
  {
    id: "headcount_utilization",
    section: "demand",
    order: 7,
    branch: "industrial",
    parentId: "customer_count",
    label: "Headcount utilization",
    helper: "e.g. 50 field workers at roughly 70% utilized. Fine to say you don't know.",
    widget: "text",
    required: false,
    validate: opt(),
    aiSpec: "Workforce utilization rate. Commonly unknown — flag for follow-up if so.",
    promptLabel: "Headcount utilization",
  },
  // Technology follow-ups
  {
    id: "paid_vs_free",
    section: "demand",
    order: 8,
    branch: "technology",
    parentId: "customer_count",
    label: "Paid customers vs. free users",
    helper: "Give both numbers separately.",
    placeholder: "140 paid, 6,200 free",
    widget: "text",
    required: false,
    validate: opt(),
    aiSpec: "Paid customer count and free user count, kept as separate numbers.",
    promptLabel: "Paid vs. free",
  },
  {
    id: "usage_rates",
    section: "demand",
    order: 9,
    branch: "technology",
    parentId: "customer_count",
    label: "Usage rates",
    helper: "Active usage, not just subscription count.",
    widget: "text",
    required: false,
    validate: opt(),
    aiSpec: "Active usage rates, distinct from subscription counts.",
    promptLabel: "Usage rates",
  },
  {
    id: "retention_churn",
    section: "demand",
    order: 10,
    branch: "technology",
    parentId: "customer_count",
    label: "Retention and churn rate",
    placeholder: "88% retention, 12% annual churn",
    widget: "text",
    required: false,
    validate: opt(),
    aiSpec: "Retention rate and churn rate.",
    promptLabel: "Retention / churn",
  },
  {
    id: "deployments_design_wins",
    section: "demand",
    order: 11,
    branch: "technology",
    parentId: "customer_count",
    label: "Deployments / design wins",
    widget: "textarea",
    required: false,
    validate: opt(),
    aiSpec: "Notable deployments or design wins.",
    promptLabel: "Deployments / design wins",
  },

  // ── Market (§4.5) ───────────────────────────────────────────────────────
  {
    id: "initial_market",
    section: "market",
    order: 0,
    label: "What market can you realistically pursue now?",
    helper: "Be specific — a geography or a vertical, not 'everyone'.",
    placeholder: "Refineries within 150 miles of Mobile, Alabama.",
    widget: "textarea",
    required: true,
    validate: req(15, "Please describe your initial market (min 15 characters)"),
    aiSpec: "The specific, realistically reachable market today — geography or vertical.",
    promptLabel: "Initial market",
  },
  {
    id: "larger_opportunity",
    section: "market",
    order: 1,
    label: "What's the larger opportunity beyond that?",
    helper: "Industrial example: Mobile first, then the whole Gulf Coast. Tech example: payroll companies first, then insurance and healthcare.",
    widget: "textarea",
    required: true,
    validate: req(15, "Please describe the larger opportunity (min 15 characters)"),
    aiSpec: "The expansion opportunity beyond the initial market.",
    promptLabel: "Larger opportunity",
  },
  {
    id: "next_markets",
    section: "market",
    order: 2,
    label: "Name the specific next markets you'd enter",
    helper: "These go straight onto the market slide, so be concrete.",
    widget: "tags",
    required: true,
    validate: req(2, "Name at least one next market"),
    aiSpec: "Named specific next markets, in order of intended entry.",
    promptLabel: "Next markets",
  },
  {
    id: "tam",
    section: "market",
    order: 3,
    label: "Total addressable market (TAM)",
    helper:
      "Always required. Investors see around 100 decks a week and won't calculate this for you.",
    widget: "money",
    required: true,
    validate: req(1, "TAM is required — investors won't calculate it for you"),
    aiSpec: "Estimated total addressable market size in dollars. ALWAYS required.",
    promptLabel: "TAM",
  },
  {
    id: "tam_derivation",
    section: "market",
    order: 4,
    label: "How did you arrive at that number?",
    widget: "textarea",
    required: false,
    validate: opt(),
    aiSpec: "The method or sources behind the TAM figure.",
    promptLabel: "TAM derivation",
  },

  // ── Commercial model (§4.6) ─────────────────────────────────────────────
  {
    id: "how_get_customers",
    section: "commercial",
    order: 0,
    label: "How do you get customers?",
    widget: "textarea",
    required: true,
    validate: req(15, "Please describe how you acquire customers (min 15 characters)"),
    aiSpec: "The customer acquisition motion.",
    promptLabel: "How we acquire customers",
  },
  {
    id: "how_earn_revenue",
    section: "commercial",
    order: 1,
    label: "How do you earn revenue?",
    widget: "textarea",
    required: true,
    validate: req(15, "Please describe how you earn revenue (min 15 characters)"),
    aiSpec: "How revenue is actually earned.",
    promptLabel: "How we earn revenue",
  },
  {
    id: "how_grow_existing",
    section: "commercial",
    order: 2,
    label: "How do you grow revenue from existing customers?",
    widget: "textarea",
    required: true,
    validate: req(15, "Please describe how you grow existing accounts (min 15 characters)"),
    aiSpec: "How revenue expands within an existing customer.",
    promptLabel: "Growing existing accounts",
  },
  // Industrial follow-ups
  {
    id: "revenue_mix",
    section: "commercial",
    order: 3,
    branch: "industrial",
    parentId: "how_earn_revenue",
    label: "What do you sell — labor hours, materials, manufactured product, or a mix?",
    helper: "Example: valve repair — 5 people for about a month is ~500 hours, billed at $X.",
    widget: "textarea",
    required: false,
    validate: opt(),
    aiSpec: "Revenue composition: labour hours, materials, manufactured product, or a mix.",
    promptLabel: "Revenue mix",
  },
  {
    id: "production_capacity",
    section: "commercial",
    order: 4,
    branch: "industrial",
    parentId: "how_earn_revenue",
    label: "Current production capacity",
    helper: "People, equipment, and facilities.",
    widget: "textarea",
    required: false,
    validate: opt(),
    aiSpec: "Current production capacity in people, equipment, and facilities.",
    promptLabel: "Production capacity",
  },
  {
    id: "capacity_limit",
    section: "commercial",
    order: 5,
    branch: "industrial",
    parentId: "how_earn_revenue",
    label: "What limits how much more you can sell today?",
    widget: "textarea",
    required: false,
    validate: opt(),
    aiSpec: "The binding constraint on selling more today.",
    promptLabel: "Capacity constraint",
  },
  // Technology follow-ups
  {
    id: "pricing_model",
    section: "commercial",
    order: 6,
    branch: "technology",
    parentId: "how_earn_revenue",
    label: "Pricing model",
    placeholder: "Per-seat subscription with a usage component",
    widget: "text",
    required: false,
    validate: opt(),
    aiSpec: "Pricing model: subscription, usage-based, licence, etc.",
    promptLabel: "Pricing model",
  },
  {
    id: "sales_motion",
    section: "commercial",
    order: 7,
    branch: "technology",
    parentId: "how_get_customers",
    label: "Sales motion",
    widget: "radioPills",
    options: [
      { value: "land-and-expand", label: "Land and expand" },
      { value: "long-cycle", label: "Longer enterprise sales cycle" },
      { value: "mixed", label: "A mix" },
    ],
    required: false,
    validate: opt(),
    aiSpec: "Whether the motion is land-and-expand or a longer sales cycle.",
    promptLabel: "Sales motion",
  },
  {
    id: "sales_cycle_length",
    section: "commercial",
    order: 8,
    branch: "technology",
    parentId: "how_get_customers",
    label: "Typical sales cycle length",
    placeholder: "About 90 days",
    widget: "text",
    required: false,
    validate: opt(),
    aiSpec: "Typical length of the sales cycle.",
    promptLabel: "Sales cycle",
  },
  {
    id: "account_expansion",
    section: "commercial",
    order: 9,
    branch: "technology",
    parentId: "how_grow_existing",
    label: "How do you expand revenue within an account?",
    widget: "textarea",
    required: false,
    validate: opt(),
    aiSpec: "The in-account expansion mechanism.",
    promptLabel: "Account expansion",
  },

  // ── Competitive position (§4.7) ─────────────────────────────────────────
  {
    id: "competitors",
    section: "competition",
    order: 0,
    label: "What other choices do your customers have?",
    helper: "Name them. 'Doing nothing' counts as a competitor.",
    widget: "tags",
    required: true,
    validate: req(2, "Name at least one alternative"),
    aiSpec: "Named competitors and alternatives, including the status quo.",
    promptLabel: "Competitors",
  },
  {
    id: "differentiation",
    section: "competition",
    order: 1,
    label: "How are you different?",
    widget: "textarea",
    required: true,
    validate: req(20, "Please describe your differentiation (min 20 characters)"),
    aiSpec: "How the company differs from those alternatives.",
    promptLabel: "Differentiation",
  },
  {
    id: "staying_competitive",
    section: "competition",
    order: 2,
    label: "How do you stay competitive over time?",
    widget: "textarea",
    required: true,
    validate: req(20, "Please describe how you stay competitive (min 20 characters)"),
    aiSpec: "What sustains the advantage over time.",
    promptLabel: "Staying competitive",
  },
  {
    id: "moat_industrial",
    section: "competition",
    order: 3,
    branch: "industrial",
    parentId: "staying_competitive",
    label: "What protects your position?",
    helper: "Relationships, processes, pricing, production capability, workforce.",
    widget: "textarea",
    required: false,
    validate: opt(),
    aiSpec:
      "Industrial moat: relationships, processes, pricing, production capability, workforce.",
    promptLabel: "Competitive protection",
  },
  {
    id: "intellectual_property",
    section: "competition",
    order: 4,
    branch: "technology",
    parentId: "staying_competitive",
    label: "Intellectual property",
    helper: "Patents, proprietary data, trade secrets.",
    widget: "textarea",
    required: false,
    validate: opt(),
    aiSpec: "Intellectual property position.",
    promptLabel: "Intellectual property",
  },
  {
    id: "switching_costs",
    section: "competition",
    order: 5,
    branch: "technology",
    parentId: "staying_competitive",
    label: "Switching costs",
    helper: "How hard is it for a customer to leave?",
    widget: "textarea",
    required: false,
    validate: opt(),
    aiSpec: "How costly or difficult it is for a customer to switch away.",
    promptLabel: "Switching costs",
  },

  // ── Growth plan (§4.8) ──────────────────────────────────────────────────
  {
    id: "growth_plan",
    section: "growth",
    order: 0,
    label: "Describe your growth plan",
    helper: "The specific steps from today to where you want to be.",
    widget: "charTextarea",
    required: true,
    validate: req(30, "Please describe your growth plan (min 30 characters)"),
    aiSpec: "The growth plan: concrete steps from today to the target state.",
    promptLabel: "Growth plan",
  },
  // Industrial follow-ups
  {
    id: "growth_locations",
    section: "growth",
    order: 1,
    branch: "industrial",
    parentId: "growth_plan",
    label: "Do you need more locations?",
    helper: "Where, and what would they cost?",
    widget: "textarea",
    required: false,
    validate: opt(),
    aiSpec: "New locations needed, where, and estimated cost.",
    promptLabel: "New locations",
  },
  {
    id: "growth_people",
    section: "growth",
    order: 2,
    branch: "industrial",
    parentId: "growth_plan",
    label: "Do you need more people?",
    helper: "How many, what roles, where, and at what cost?",
    widget: "textarea",
    required: false,
    validate: opt(),
    aiSpec: "Hiring needs: headcount, roles, locations, cost.",
    promptLabel: "Additional people",
  },
  {
    id: "growth_equipment",
    section: "growth",
    order: 3,
    branch: "industrial",
    parentId: "growth_plan",
    label: "Do you need more equipment?",
    helper: "Include automation or robotics that would replace manual work.",
    widget: "textarea",
    required: false,
    validate: opt(),
    aiSpec: "Equipment needs including automation/robotics, and cost.",
    promptLabel: "Equipment needs",
  },
  {
    id: "expansion_scope",
    section: "growth",
    order: 4,
    branch: "industrial",
    parentId: "growth_plan",
    label: "Expansion scope",
    widget: "radioPills",
    options: [
      { value: "local", label: "Local" },
      { value: "statewide", label: "Statewide" },
      { value: "regional", label: "Regional" },
      { value: "national", label: "National" },
    ],
    required: false,
    validate: opt(),
    aiSpec: "Geographic ambition: local, statewide, regional, or national.",
    promptLabel: "Expansion scope",
  },
  // Technology follow-ups — deliberately no location questions.
  {
    id: "product_roadmap",
    section: "growth",
    order: 5,
    branch: "technology",
    parentId: "growth_plan",
    label: "Product roadmap",
    helper: "Major releases over the next 6, 12 and 18 months.",
    widget: "textarea",
    required: false,
    validate: opt(),
    aiSpec: "Product roadmap over the next 6, 12 and 18 months.",
    promptLabel: "Product roadmap",
  },
  {
    id: "rd_hiring",
    section: "growth",
    order: 6,
    branch: "technology",
    parentId: "growth_plan",
    label: "R&D hiring needs",
    widget: "textarea",
    required: false,
    validate: opt(),
    aiSpec: "Research and engineering hiring needs.",
    promptLabel: "R&D hiring",
  },
  {
    id: "compute_costs",
    section: "growth",
    order: 7,
    branch: "technology",
    parentId: "growth_plan",
    label: "Compute and infrastructure costs",
    helper: "Cloud spend, or data-centre needs if you build physical infrastructure.",
    widget: "textarea",
    required: false,
    validate: opt(),
    aiSpec: "Compute/infrastructure cost trajectory, including cloud spend.",
    promptLabel: "Compute / infrastructure",
  },

  // ── Financial picture (§4.9) ────────────────────────────────────────────
  {
    id: "historicals",
    section: "financials",
    order: 0,
    label: "Historical performance",
    helper: "Revenue and profit or loss for the last three years.",
    widget: "textarea",
    required: true,
    validate: req(15, "Please give some history (min 15 characters)"),
    aiSpec: "Revenue and profit/loss for the last three years.",
    promptLabel: "Historical performance",
    allowAttachments: true,
  },
  {
    id: "forecast",
    section: "financials",
    order: 1,
    label: "Forecast",
    helper: "Where you expect revenue to land over the next three years.",
    widget: "projections",
    required: true,
    validate: req(10, "Please add at least one forecast year"),
    aiSpec: "Revenue forecast for the next three years.",
    promptLabel: "Forecast",
    allowAttachments: true,
  },
  {
    id: "forecast_assumptions",
    section: "financials",
    order: 2,
    label: "Key assumptions behind the forecast",
    helper: "This is the first thing a CFO will pull on.",
    widget: "textarea",
    required: true,
    validate: req(20, "Please list your key assumptions (min 20 characters)"),
    aiSpec: "The assumptions the forecast depends on.",
    promptLabel: "Forecast assumptions",
  },
  {
    id: "current_burn",
    section: "financials",
    order: 3,
    label: "Monthly burn",
    widget: "money",
    required: false,
    validate: opt(),
    aiSpec: "Monthly cash burn, if the company is burning cash.",
    promptLabel: "Monthly burn",
  },

  // ── Team (§4.10) ────────────────────────────────────────────────────────
  {
    id: "team_members",
    section: "team",
    order: 0,
    label: "Who is responsible for executing this plan?",
    helper: "Name, role, and the experience that makes them right for it.",
    widget: "teamRepeater",
    required: true,
    validate: z
      .array(teamMemberSchema)
      .min(1, { error: "Add at least one team member" })
      .max(8, { error: "Maximum 8 team members" }),
    aiSpec: "Key people: name, role, and relevant background for each.",
    promptLabel: "Team",
  },
  {
    id: "industry_experience",
    section: "team",
    order: 1,
    label: "What experience does the team have in this industry?",
    helper: "Industry experience specifically is a strong plus for investors.",
    widget: "textarea",
    required: true,
    validate: req(20, "Please describe the team's industry experience (min 20 characters)"),
    aiSpec: "Team experience in this specific industry — treated as a plus.",
    promptLabel: "Industry experience",
  },
  {
    id: "key_hires",
    section: "team",
    order: 2,
    label: "Key hires planned with this raise",
    widget: "textarea",
    required: false,
    validate: opt(),
    aiSpec: "Roles the company plans to hire with the new money.",
    promptLabel: "Planned key hires",
  },

  // ── The ask (§4.11) ─────────────────────────────────────────────────────
  {
    id: "raise_amount",
    section: "raise",
    order: 0,
    label: "How much are you raising?",
    widget: "money",
    required: true,
    validate: req(1, "Raise amount is required"),
    aiSpec: "The amount being raised.",
    promptLabel: "Raise amount",
  },
  {
    id: "use_of_funds",
    section: "raise",
    order: 1,
    label: "Use of funds",
    helper: "Break it into three or four buckets with dollars or percentages.",
    widget: "allocation",
    required: true,
    validate: req(8, "Add at least one category with its percentage"),
    aiSpec: "Use of funds, broken into three or four categories with amounts or percentages.",
    promptLabel: "Use of funds",
  },
  {
    id: "runway_months",
    section: "raise",
    order: 2,
    label: "How long will this money last?",
    helper: "Runway in months.",
    widget: "slider",
    required: true,
    validate: req(1, "Runway is required"),
    aiSpec: "Runway in months that the raise buys.",
    promptLabel: "Runway (months)",
  },
  {
    id: "milestone",
    section: "raise",
    order: 3,
    label: "What milestone does it get you to?",
    helper:
      "Tech example: $15M → new R&D team + 18 months runway → profitability. Industrial example: $XM → cranes + Mobile and Pensacola yards → cut long-haul equipment costs.",
    widget: "textarea",
    required: true,
    validate: req(15, "Please describe the milestone (min 15 characters)"),
    aiSpec: "The milestone this raise gets the company to.",
    promptLabel: "Milestone",
  },
];

/** Fast id → definition lookup. */
export const QUESTIONS_BY_ID: Record<string, QuestionDef> = Object.fromEntries(
  QUESTION_BANK.map((q) => [q.id, q])
);

if (process.env.NODE_ENV !== "production") {
  const seen = new Set<string>();
  for (const q of QUESTION_BANK) {
    if (seen.has(q.id)) throw new Error(`Duplicate question id in bank: ${q.id}`);
    seen.add(q.id);
  }
  for (const q of QUESTION_BANK) {
    if (q.parentId && !seen.has(q.parentId)) {
      throw new Error(`Question ${q.id} references unknown parentId ${q.parentId}`);
    }
  }
}
